export { default as AboutSection } from './AboutSection'
export { default as KnowledgeSection } from './KnowledgeSection'
export { default as ExperienceSection } from './ExperienceSection'
export { default as StudiesSection } from './StudiesSection'
export { default as ContactSection } from './ContactSection'